"""update user

Revision ID: 9db3a2bc6535
Revises: 425e43a1dae6
Create Date: 2026-06-07 21:56:45.837769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db3a2bc6535'
down_revision: Union[str, Sequence[str], None] = '425e43a1dae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        'users',
        sa.Column(
            'created_time',
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute("""
        UPDATE users
        SET created_time = NOW()
        WHERE created_time IS NULL
    """)

    op.alter_column(
        'users',
        'created_time',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_time')
    op.drop_column('users', 'created_time')
    op.create_table('email_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_codes_pkey'))
    )
    op.create_index(op.f('ix_email_codes_email'), 'email_codes', ['email'], unique=False)
    # ### end Alembic commands ###
